# Generated by Django 3.2.12 on 2022-03-29 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Content', models.TextField()),
                ('Create_time', models.DateTimeField(default=datetime.datetime.now)),
                ('Completed', models.BooleanField(default=False)),
                ('Completition_date', models.DateTimeField(blank=True, null=True)),
                ('User_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='todoprojectapp.register')),
            ],
        ),
    ]
